export {
  DEFAULT_SCHEMA_LOAD_TIMEOUT_MS,
  extractDocumentSchemaKey,
  findSchemaConfigForDocument,
  loadSchemaSource,
  loadSchemaSourceSync,
  resolveDocumentSchemaSources,
  resolveWorkspaceRoot,
  schemaLoading as default,
  type DocumentSchemaConfig,
  type InitializeParamsLike,
  type SchemaLoadContext,
  type SchemaLoadResult,
  type SchemaLoadSyncContext,
  type SchemaPatterns,
  type ServerInitializationOptions,
} from '@templjs/language-service';
