export const wiBaselineFunctions = {
  string: [
    'upper',
    'lower',
    'capitalize',
    'trim',
    'ltrim',
    'rtrim',
    'replace',
    'slice',
    'split',
    'join',
    'startsWith',
    'endsWith',
    'includes',
    'indexOf',
    'padStart',
    'padEnd',
    'repeat',
    'reverse',
    'escape',
  ],
  number: [
    'round',
    'floor',
    'ceil',
    'abs',
    'min',
    'max',
    'clamp',
    'sqrt',
    'pow',
    'log',
    'exp',
    'sin',
    'cos',
    'tan',
    'sum',
    'avg',
    'product',
  ],
  datetime: [
    'now',
    'format',
    'parse',
    'addDays',
    'addHours',
    'addMinutes',
    'getYear',
    'getMonth',
    'getDay',
    'getHour',
    'timezone',
    'timestamp',
  ],
  array: [
    'length',
    'first',
    'last',
    'nth',
    'reverse',
    'sort',
    'unique',
    'flatten',
    'slice',
    'concat',
    'join',
    'filter',
    'map',
    'find',
    'includes',
    'indexOf',
  ],
  object: ['keys', 'values', 'entries', 'has', 'get', 'merge', 'pick', 'omit', 'length'],
  utility: ['default', 'typeof', 'string', 'number', 'json'],
} as const;

export const extendedFunctions = [
  'sign',
  'toFixed',
  'parseInt',
  'parseFloat',
  'isNaN',
  'isFinite',
  'size',
  'reduce',
  'assign',
  'isEmpty',
  'getDate',
  'getDayOfWeek',
  'toISO',
  'fromISO',
  'diff',
] as const;
